const regions = [
  { name: "Polynesia", shape: 0, color: "#676767" },
  { name: "Melanesia", shape: 0, color: "#5A20A3" },
  { name: "Southern Africa", shape: 0, color: "#E08F56" },
  { name: "Central America", shape: 0, color: "#B6050F" },
  { name: "Caribbean", shape: 0, color: "#B6050F" },
  { name: "Middle Africa", shape: 0, color: "#E08F56" },
  { name: "Northern Africa", shape: 0, color: "#E08F56" },
  { name: "South America", shape: 0, color: "#AF70A5" },
  { name: "Eastern Africa", shape: 0, color: "#E08F56" },
  { name: "Western Africa", shape: 0, color: "#E08F56" },
  { name: "South-eastern Asia", shape: 1, color: "#F6CC52" },
  { name: "Eastern Asia", shape: 1, color: "#F6CC52" },
  { name: "Central Asia", shape: 1, color: "#F6CC52" },
  { name: "Southern Europe", shape: 1, color: "#78B2EB" },
  { name: "Northern Europe", shape: 1, color: "#78B2EB" },
  { name: "Australia and New Zealand", shape: 0, color: "#AFD164" },
  { name: "Western Asia", shape: 1, color: "#F6CC52" },
  { name: "Southern Asia", shape: 1, color: "#F6CC52" },
  { name: "Western Europe", shape: 1, color: "#78B2EB" },
  { name: "Eastern Europe", shape: 1, color: "#78B2EB" },
  { name: "Northern America", shape: 0, color: "#AF70A5" },
];
export default regions;
