const regions = [
  {
    name: "Polynesia",
    shape: 0,
    color: "#5C800B",
    colorLight: "#ADC085",
    code: "957",
  },
  {
    name: "Melanesia",
    shape: 0,
    color: "#5C800B",
    colorLight: "#ADC085",
    code: "928",
  },
  {
    name: "Southern Africa",
    shape: 0,
    color: "#E08F56",
    colorLight: "#F0C7AB",
    code: "913",
  },
  {
    name: "Central America",
    shape: 0,
    color: "#AF70A5",
    colorLight: "#D7B7D2",
    code: "916",
  },
  {
    name: "Caribbean",
    shape: 0,
    color: "#AF70A5",
    colorLight: "#D7B7D2",
    code: "915",
  },
  {
    name: "Middle Africa",
    shape: 0,
    color: "#E08F56",
    colorLight: "#F0C7AB",
    code: "911",
  },
  {
    name: "Northern Africa",
    shape: 0,
    color: "#E08F56",
    colorLight: "#F0C7AB",
    code: "912",
  },
  {
    name: "South America",
    shape: 0,
    color: "#AF70A5",
    colorLight: "#D7B7D2",
    code: "931",
  },
  {
    name: "Eastern Africa",
    shape: 0,
    color: "#E08F56",
    colorLight: "#F0C7AB",
    code: "910",
  },
  {
    name: "Western Africa",
    shape: 0,
    color: "#E08F56",
    colorLight: "#F0C7AB",
    code: "914",
  },
  {
    name: "South-eastern Asia",
    shape: 1,
    color: "#F6CC52",
    colorLight: "#FAE5A8",
    code: "920",
  },
  {
    name: "Eastern Asia",
    shape: 1,
    color: "#F6CC52",
    colorLight: "#FAE5A8",
    code: "906",
  },
  {
    name: "Central Asia",
    shape: 1,
    color: "#F6CC52",
    colorLight: "#FAE5A8",
    code: "5500",
  },
  {
    name: "Southern Europe",
    shape: 1,
    color: "#78B2EB",
    colorLight: "#BBD8F5",
    code: "925",
  },
  {
    name: "Northern Europe",
    shape: 1,
    color: "#78B2EB",
    colorLight: "#BBD8F5",
    code: "924",
  },
  {
    name: "Australia and New Zealand",
    shape: 0,
    color: "#5C800B",
    colorLight: "#ADC085",
    code: "927",
  },
  {
    name: "Western Asia",
    shape: 1,
    color: "#F6CC52",
    colorLight: "#FAE5A8",
    code: "922",
  },
  {
    name: "Southern Asia",
    shape: 1,
    color: "#F6CC52",
    colorLight: "#FAE5A8",
    code: "5501",
  },
  {
    name: "Western Europe",
    shape: 1,
    color: "#78B2EB",
    colorLight: "#BBD8F5",
    code: "926",
  },
  {
    name: "Eastern Europe",
    shape: 1,
    color: "#78B2EB",
    colorLight: "#BBD8F5",
    code: "923",
  },
  {
    name: "Northern America",
    shape: 0,
    color: "#AF70A5",
    colorLight: "#D7B7D2",
    code: "905",
  },
];
export default regions;
